### ISSUE TITLE
Is JEXL filtering an anti-pattern?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/remote-settings#111]
Coming out of the Experiments work week, targeting/filtering is quite hard to get right.  Should we deprecate/remove JEXL filtering from remote-settings?

**Comment by leplatrem** [comment]
They are not heavily used in Remote Settings. AFAIK it's used in `security-state` to target by version only.

**Comment by mostlygeek** [comment]
I iterated through all the current "[in prod](https://docs.google.com/spreadsheets/d/1TogKspQnTPkYAKrZNZG3bf8MiETBm2lYHfl0wKd2BS4/edit#gid=0)" collections in remote-settings with this script: 

```
#!/usr/bin/env bash

for URL in `cat collections.txt`
do
    echo "$URL"
    curl -s $URL | jq -c '.data[] | {id:.id, filter_expression:.filter_expression}' | grep -v null
    echo
done
```

And there are only two records using filter_expressions: 

```
https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/url-classifier-skip-urls/records
{"id":"bd824c89-4626-426c-b6bf-751f53aec05e","filter_expression":"env.channel == \"release\""}
{"id":"90467a71-2510-49a2-9a51-0071af0aeafc","filter_expression":"env.channel == \"release\""}
```

The usage is low.   I think the action item here is to update the documentation a bit to reflect these points to address some feedback I've heard.

1.  Confusion when only *some* records appear on a get call.  This made debugging confusing when people forget what effect filtering has on `.get()`. 
1.  Call out that the feature is for "advanced" users.  Using the `filter_expressions` means you always have to keep in mind that users will likely get a different collection. 

Also (maybe these are improvements?): 

- FilterObjects can replace the pure jexl.  Less power but more intuitive and obvious behaviour
- Make "targeting" a unified, reusable and intuitive primitive in the client that RS is a consumer of
- ???

**Comment by leplatrem** [comment]
> FilterObjects can replace the pure jexl. Less power but more intuitive and obvious behaviour

We had them in mind, and at the time we decided that the UI would be in charge of translating them to JEXL expressions.

> Make "targeting" a unified, reusable and intuitive primitive in the client that RS is a consumer of

Yes, I think that would make sense. I felt a bit disappointed to discover after the fact that some use-cases redeveloped similar features...
