### ISSUE TITLE
Readthedocs site lists copyright date of 2018, making people (me!) think it's out of date

### ISSUE THREAD

**Issue by gijsk** [mozilla/remote-settings#112]
E.g. bottom of https://remote-settings.readthedocs.io/en/latest/tutorial-normandy-integration.html

**Comment by leplatrem** [comment]
![Screenshot from 2020-05-07 16-22-17](https://user-images.githubusercontent.com/546692/81305712-f346bd80-907e-11ea-9849-39c86a7913fe.png)
