### ISSUE TITLE
Review page not rendering properly

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/remote-settings#127]
On my local remote settings instance the review page looks like this:

<img width="1157" alt="Screen Shot 2021-07-06 at 12 30 16 PM" src="https://user-images.githubusercontent.com/119884/124952904-a0e69100-dfe2-11eb-873e-958039fd9dc3.png">

**Comment by leplatrem** [comment]
Restored to Bootstrap 4 in STAGE

**Comment by leplatrem** [comment]
This was fixed, sorry about that regression
