### ISSUE TITLE
[Stage] Remote Settings Simple Review returns a blank page when accessed

### ISSUE THREAD

**Issue by heres-maria** [mozilla/remote-settings#129]
**[Prerequisites]:**
- Be connected to the corporate VPN.

**[Steps to reproduce]:**
1. Navigate to “https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/simple-review ”.
2. Observe the page.

**[Expected result]:**
- The login prompt is displayed if not logged in and after login the page is displayed.

**[Actual result]:**
- The page is blank.

**[Notes]:**
- I can access https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/records, though that page is also blank sometimes.
- The page worked for me today, it started behaving that way while I was testing Nimbus experiments which required me to approve/reject multiple experiments.
- Attached is a screen recording of the issue.
![blank RS](https://user-images.githubusercontent.com/53752296/133802740-fc1e7bca-cb40-42c2-8885-de4772b20764.gif)

**Comment by heres-maria** [comment]
From a discussion with @jaredlockhart, it seems production is not affected.

**Comment by leplatrem** [comment]
We've just deployed a new build, it is fixed :) Sorry for the inconvenience

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. I can now successfully access both the [Simple Review](https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/simple-review) and [Records](https://settings-writer.stage.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/records) pages without them being blank. Tested using Firefox Nightly 94.0a1 (Build ID: 20210920212918) and Google Chrome 93.0.4577.82.
