### ISSUE TITLE
Document whole ecosystem

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#13]
List stuff like https://github.com/mozilla-services/amo2kinto-lambda

and https://github.com/mozilla-services/cloudops-deployment/tree/dc72e8241f5f721e49c054c8726a4fc4a7089b61/projects/kinto-lambda/ansible/playbooks

- [x] Clean up management of blocklist schemas
- [x] Clean up amo2kinto repo
- [ ] Rename amo2kinto to remote-settings where relevant
- [x] Document lambda

**Comment by leplatrem** [comment]
There is also amo-blocklist-ui, is it still used? https://github.com/mozilla-services/amo-blocklist-ui/
The lambda is not documented in amo2kinto-lambda

But also some other collections have their schema there: https://github.com/mozilla-services/cloudops-deployment/blob/761e4fbc63da11778347187ce92c24c4520000b0/projects/kinto/puppet/yaml/permissions/kinto.prod.yaml#L114

**Comment by mostlygeek** [comment]
I don't think this needs to be part of any of the projects. We can do this when we have a "cleanup" iteration.  I'm taking it out of the V1.2 project. Please add it back in if you disagree.

**Comment by leplatrem** [comment]
I consider this done.
