### ISSUE TITLE
Merge kinto-changes + kinto-signer into `kinto-remote-settings`

### ISSUE THREAD

**Issue by grahamalama** [mozilla/remote-settings#132]
- These are the two Mozilla-specific plugins of kinto-dist
- Would make it clear that remote-settings = kinto + kinto-remote-settings
- kinto-changes is small and would be trivial to merge into kinto-signer

**Comment by grahamalama** [comment]
Per discussion with @leplatrem: [`Kinto/kinto-signer`](https://github.com/Kinto/kinto-signer) was forked into the Mozilla Services org ([`mozilla-services/kinto-signer`](mozilla-services/kinto-signer)). Plan is to merge [`Kinto/remote-changes`](https://github.com/Kinto/kinto-changes) into `mozilla-services/kinto-signer` and rename the repo to `kinto-remote-settings`.

**Comment by leplatrem** [comment]
Do you have the rights to add SysEng to be admins of mozilla-services/kinto-signer?

**Comment by grahamalama** [comment]
> Do you have the rights to add SysEng to be admins of mozilla-services/kinto-signer?

Yep! Done.

**Comment by grahamalama** [comment]
This ticket is slightly outdated. Instead of the plan above, we've combined `changes` and `signer` in a package `kinto_remote_settings` directly in `kinto-dist` (https://github.com/mozilla-services/kinto-dist/pull/1934).
