### ISSUE TITLE
Document loadDumpIfNewer

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/remote-settings#136]
in [bug 1717068](https://bugzilla.mozilla.org/show_bug.cgi?id=1717068), Rob introduced a new option, `loadDumpIfNewer`, on the `get()` call [hg commit](https://hg.mozilla.org/integration/autoland/rev/cd7ca21b05e9).  This option isn't easy to discover in the [Remote Settings source documentation](https://firefox-source-docs.mozilla.org/services/settings/index.html#initial-data).  

- [ ] Write Firefox Source Docs documentation for this option with appropriate links to the bug.  
- [ ] Write a new [case study](https://remote-settings.readthedocs.io/en/latest/case-studies.html) about how his feature is used in production

This is the [original slack conversation](https://mozilla.slack.com/archives/CBGR8AW6R/p1637698389038200) that triggered this issue.

**Comment by leplatrem** [comment]
`loadDumpIfNewer`  is now enabled by default everywhere. I don't think we want to invite users to disable it (option is only used in tests and will be removed soon)
