### ISSUE TITLE
Remove hard-coded collection lists in Firefox settings lambdas

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#14]
See https://github.com/mozilla-services/amo2kinto-lambda 

Ref #3 

* [x] Modify lambda code to get values from server (changes, capabalities, etc.)
* [x] Deploy new version to STAGE https://bugzilla.mozilla.org/show_bug.cgi?id=1445263
* [ ] Deploy new version to PROD  https://bugzilla.mozilla.org/show_bug.cgi?id=1445336
* [ ] Cleanup and remove hard-coded values from cloudops playbooks

**Comment by leplatrem** [comment]
In order to refresh a signature from the command-line, we can use a simple `curl` request:

```
curl --request PATCH https://settings-writer.prod.mozaws.net/v1/buckets/staging/collections/qa -d '{"data":{"status":"to-sign"}}' -H 'Content-Type:application/json' -u admin@mozilla.com:pass
```

And it has to be done on:
- `/buckets/staging/collections/qa`  *(was not mentioned in hard-coded list before and has expired)*
- `/buckets/pinning/collections/pins`  *(to leverage a bugfix deployed in January)*

In the case of GFX, we have to refresh the preview collection signature, so we need two persons :) The first one has to trigger a review, and the second has to sign it off. It should work without having to make any changes to the data.

user 1:
```
curl --request PATCH https://settings-writer.prod.mozaws.net/v1/buckets/staging/collections/gfx -d '{"data":{"status":"to-review"}}' -H 'Content-Type:application/json' -u admin1@mozilla.com:pass
```
user 2:
```
curl --request PATCH https://settings-writer.prod.mozaws.net/v1/buckets/staging/collections/gfx -d '{"data":{"status":"to-sign"}}' -H 'Content-Type:application/json' -u admin2@mozilla.com:pass
```

**Comment by mostlygeek** [comment]
Update: will pick this up next week at the kinto meeting.  Will ask ops to trigger the signature resign to get this moving forward.

**Comment by bqbn** [comment]
@leplatrem and I have run the following for the `qa` and `pins` collections,
```
curl --request PATCH https://settings-writer.prod.mozaws.net/v1/buckets/staging/collections/qa -d '{"data":{"status":"to-sign"}}' -H 'Content-Type:application/json' -u <user>:<pass>
curl --request PATCH https://settings-writer.prod.mozaws.net/v1/buckets/pinning-staging/collections/pins -d '{"data":{"status":"to-sign"}}' -H 'Content-Type:application/json' -u <user>:<pass>
```

And we have run the following for the `gfx` collection,
```
curl --request PATCH https://settings-writer.prod.mozaws.net/v1/buckets/staging/collections/gfx -d '{"data":{"status":"to-review"}}' -H 'Content-Type:application/json' -u <user>:<pass>
curl --request PATCH https://settings-writer.prod.mozaws.net/v1/buckets/staging/collections/gfx -d '{"data":{"status":"work-in-progress"}}' -H 'Content-Type:application/json' -u <user>:<pass>
```

I think someone needs to review then approve for the `gfx` collection.

@leplatrem can you confirm we can proceed with https://bugzilla.mozilla.org/show_bug.cgi?id=1445336 now, or wait for `gfx` collection to be reviewed and approved?

**Comment by bqbn** [comment]
Never mind. I just saw https://bugzilla.mozilla.org/show_bug.cgi?id=1445336#c1 and deployed v4.0.2 to -prod.
