### ISSUE TITLE
CDN caching issue after signature refresh 

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#186]
Users reported certificate expiration errors, from two different contexts (Merino Rust client and Desktop Firefox).

> pjenvey> FYI, this morning merino began reporting certificate expired errors when verifying RS signatures
> pjenvey> it's using the rust remote settings client. almost wondered if it was a false alarm but I noticed some talk of expired certs recently
>

> jschanck> I'm seeing invalid signatures for a few collections when using the remote-settings-devtools extension. Hitting "clear local data" followed by "force sync" on main/message-groups gives me InvalidSignatureError: Invalid content signature (main/message-groups) . Same for main/personality-provider-models
>
> jschanck> I dumped the cert chain here: https://searchfox.org/mozilla-central/source/services/settings/RemoteSettingsClient.jsm#861 and it is using the [expired one](https://content-signature-2.cdn.mozilla.net/chains/remote-settings.content-signature.mozilla.org-2022-03-01-08-35-12.chain) rather than the one listed in the [collection metadata](https://content-signature-2.cdn.mozilla.net/chains/remote-settings.content-signature.mozilla.org-2022-04-10-18-14-48.chain).

The error could not be reproduced the following day. 

This could indicate a CDN caching issue.

When synchronization happens from a push notification, the current data timestamp is passed in the `?_expected=` query param, in order to bust the CDN cache.

However there are several situations where the synchronization happens without push notification, and in these cases the current data timestamp is taken from the [monitor/changes](https://firefox.settings.services.mozilla.com/v1/buckets/monitor/collections/changes/records) endpoint. 

Regularly we refresh the collections signature, to make sure the metadata always point to the latest certificate chain. However, this operation doesn't «bump» the data timestamp. 

The following scenario seems to be the culprit:

1. changes are made on collection X, data timestamp is bumped (`timestamp=42`)
2. clients pull data from push notification, changeset is [aggressively cached](https://github.com/mozilla/remote-settings/blob/d1996490b2f5dc7f4d098c14f89dc86f3f568ca1/kinto-remote-settings/src/kinto_remote_settings/changes/views.py#L126-L138) on the CDN with `_expected=42` (for [1 hour](https://github.com/mozilla-services/cloudops-deployment/blob/b2ed06d77b6d84860b7bada0834c866fe37b289f/projects/kinto/puppet/modules/kinto/templates/kinto.ini.erb#L144))
3. signature is refreshed, the collection metadata is updated, data timestamp remains the same
4. client synchronizes from scratch, queries monitor/changes endpoint, `timestamp=42`, pull changeset with `_expected=42`
5. CDN returns the outdated changeset. 

This may happen in the following contexts:
- Rust client (does not use push notifs)
- sync from scratch (scheduled or on startup)
- manual sync

# Possible Approaches

## Do nothing

**pros**

- No change, no risk

**cons**

- Affect reliability of the service
- Signature verification will fail on clients, even after retrying from scratch

## Bump data timestamp on signature refresh

**pros**

- No code change in the client, the fix can be deployed on the server immediately, no trains riding
- Clients will always fetch the latest version
- Clients will «revalidate» their local data signature on certificate refresh
- Fix will apply to both Rust and Desktop client
 
**cons**

- After a signature refresh, the clients will poll the server, obtain the latest certificate metadata, but obtain zero data change. This will increase the traffic on our servers (not origins though).

## Change client behavior

For example, add the metadata timestamp in the monitor/changes along the data timestamp, and if signature fails, the client retries using the metadata timestamp instead of the data timestamp as CDN cache bust.

**pros**

- Finer control of behaviour

**cons**

- Increases complexity
- Must ride trains...
- Must be implemented in Rust client too

**Comment by leplatrem** [comment]
Another option could be to revamp a similar approach than the one we had years ago:  make a call on the CDN management API to invalidate the cache.

The refresh signature lambda would:
- update the metadata of the few collections that weren't changed for more than 7 days
- make a call to the GCP CDN API to invalidate the `/buckets/{bid}/collections/{cid}/changeset` and `/buckets/{bid}/collections/{cid}` endpoints
- on cache miss, the GCP will refetch the origin response, that will contain the new metadata
- clients that will fetch the data using the old records timestamp as `?_expected={}` will obtain the fresh data immediately. 
- the CDN will cache the source forever until the records are changed (different timestamp in `?_expected`) or until the signature is refreshed, because the origin's `Last-Modified` will remain the same meanwhile. See #326

**Comment by smarnach** [comment]
In general, relying on cache invalidations has some downsides. It ties us more closely to the CDN we are using (even though I hope that we won't be migrating again anytime soon). Moreover, cache invalidations are also kind of slow on Cloud CDN. I think the one we had yesterday finished after 15 minutes or so. Google also [recoomends against using invalidations on a regular basis](https://cloud.google.com/cdn/docs/cache-invalidation-overview#limitations).

My favourite solution is bumping the data timestamp on signature refresh – the additional traffic should be manageable. We could also consider reducing the frequency of the refresh-signature lambda to, say, once a week.
