### ISSUE TITLE
.authType should be equal to one of the allowed values error

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/remote-settings#229]
Following the steps [here](https://remote-settings.readthedocs.io/en/latest/tutorial-local-server.html#simple-mode-testing) I am running into an error message that says ```.authType should be equal to one of the allowed values```. Trying to login without a username and password doesn't work as the site says the fields are required.

**Comment by grahamalama** [comment]
Hey @jrbenny35, thanks for submitting this issue. At first glance, it seems like this could be a bug with https://www.github.com/Kinto/kinto-admin. If it isn't, it could be an area where we could be more clear in the docs with how to use published container with the suggested configuration file (`config/testing.ini`).

In the meantime, if you want to get a local instance of Remote Settings running, I'd recommend cloning this repo and running `make build`.

**Comment by leplatrem** [comment]
This is weird, I followed the steps, and got:
```
$ docker run -v `pwd`/attachments:/tmp/attachments \
           -e KINTO_INI=config/testing.ini \
           -p 8888:8888 \
           mozilla/remote-settings
[uWSGI] getting INI configuration from config/testing.ini
[uwsgi-static] added mapping for /attachments => /tmp/attachments
*** Starting uWSGI 2.0.20 (64bit) on [Thu Jun 16 05:48:12 2022] ***
...
...
/opt/venv/lib/python3.10/site-packages/kinto/core/initialization.py:567: UserWarning: HTTPS is not enabled
  warnings.warn("HTTPS is not enabled")
Running Remote Settings TESTING 14.7.2.
Running Remote Settings TESTING 14.7.2.
...
```

Then open http://localhost:8888/v1 and have this:
<img width="836" alt="Screenshot 2022-06-16 at 17 30 22" src="https://user-images.githubusercontent.com/546692/174106091-45103804-82b6-4c2a-9ecb-aae143686c1e.png">


which leads me to the homepage.

<img width="696" alt="Screenshot 2022-06-16 at 17 29 23" src="https://user-images.githubusercontent.com/546692/174105954-c666b62a-8921-4180-8814-9876c467f366.png">


Sadly, retrieving the list of collections crashes the server when an object is created by an anonymous. But this is unrelated and we should be able to fix it (https://github.com/Kinto/kinto/issues/2687)

**Comment by leplatrem** [comment]
Upstream issue was closed https://github.com/Kinto/kinto-admin/issues/3065
