### ISSUE TITLE
Nimbus and Normandy experiments can no longer be launched on Stage or Stage Preview

### ISSUE THREAD

**Issue by heres-maria** [mozilla/remote-settings#275]
**[Prerequisites]**:
- Be connected to the Mozilla VPN.
- Have a [Nimbus](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus) draft ready for launch.

**[Steps to reproduce]**:
1. Have someone else request the launch of the draft from prerequisites.
2. Navigate to the draft’s page.
3. Click “Approve and Launch Experiment”.
4. Click “Open Remote Settings”.
5. Observe the page.

**[Expected result]**:
- Experiments can be approved or rejected from RS.

**[Actual result]**:
- Experiments can not be approved or rejected from RS. 

**[Notes]**:
- The /records page displays a “Request review” button, but adding a message and trying to request the review leads to an error message.
- The issue also seems reproducible for Stage Preview, where experiments are not directly launched.
- This issue also seems reproducible for Normandy experiments created using the Normandy Devtools extension. An experiment launched was not displayed in https://settings.stage.mozaws.net/v1/buckets/main/collections/normandy-recipes-capabilities/records.
- Attached are a recording and a screenshot of the issue.

![trying to launch experiment](https://user-images.githubusercontent.com/53752296/189083096-ca91bf13-bc3a-4f30-a2f0-b6bf3a479188.gif)
![image_2022_09_08T08_29_33_846Z](https://user-images.githubusercontent.com/53752296/189083199-8a3462e5-fe1b-48a5-9ade-12049695e679.png)

**Comment by smarnach** [comment]
This is a problem with Autograph stage, one of the backend services of Remote Settings. I've informed the operators of Autograph on Slack.

**Comment by jaredlockhart** [comment]
I just tested on stage and was unable to reproduce, has this now been fixed?

**Comment by mlarsonweber** [comment]
We have deployed the changes to Stage: including the new signer config for the VPN as well as a new certificate. This should be fixed

**Comment by jaredlockhart** [comment]
@heres-maria When you're back please verify whether you're able to reproduce this.  Thank you for the fix @mlarsonweber !

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible on Stage. Experiments can now be approved or rejected in RS and they can be launched. Tested on Firefox Release 104.0.2 (Build ID: 20220902153754) on Windows 10.
