### ISSUE TITLE
[Gecko client] filtered list of entries on change ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#28]
We know that `.get()` returns a filtered list based on the target info (jexl for platform etc.).

But what about the change event ?

```js
RemoteSettings("key")
  .on("change", ({data, created, updated, deleted}) => {
    // ...
  })
```

Intuitively I would assume the `data`, `updated` and `deleted` values comed filtered, and that if the `created + updated + deleted` set is empty then the `on("change")` callback is not called at all.

**Comment by glasserc** [comment]
That sounds fine to me.

**Comment by leplatrem** [comment]
Follow up implementation in #37
