### ISSUE TITLE
Collection root API endpoints return `no-store` directive, which is ignored by CloudFront

### ISSUE THREAD

**Issue by smarnach** [mozilla/remote-settings#300]
The root API endpoint for each collection includes the response header

    Cache-Control: no-cache, no-store

CloudFront caches these endpoints anyway. So either we've been doing this wrong for years, or we can change the Cache-Control header for these endpoints to allow caching as well. It would be much preferable if the answer is the latter.

**Comment by leplatrem** [comment]
According to the code:
https://github.com/Kinto/kinto/blob/3a806a426a3b96b2344b52f6ac1832cb25821cbc/kinto/core/resource/__init__.py#L497-L516

This could be solved by adding in the settings:
```ini
kinto.collection_cache_expires_seconds = 3600
```

**Comment by smarnach** [comment]
The PR fixed this in stage.
