### ISSUE TITLE
Recipes on the Normandy Stage server are not loading and new actions can't be configured

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/remote-settings#329]
[Prerequisites]:
- Be connected to the Mozilla VPN.
- Have the [Normandy Devtools](https://github.com/mozilla-extensions/normandy-devtools/releases) addon installed.

[Steps to reproduce]:
1. Click the Normandy Devtools icon from the toolbar.
2. Click the Environment button from the top right part of the page.
3. Select Stage from the dropdown menu.
4. Observe the behavior.

[Expected result]:
- All staging recipes are displayed and the Environment button has a green dot in its corner.

[Actual result]:
- A "Loading recipes..." message is displayed continuously and the Environment button does not have a green dot in its corner.

[Notes]:
- The Prod and Dev servers do not seem affected by this issue. In those cases the recipes are loaded successfully and the green dot remains in its place.
- Attached are a recording and a screenshot of the issue.

https://user-images.githubusercontent.com/18304511/203751646-4453949f-e84b-40e0-9810-9a9a016e7104.mp4

**Comment by SoftVision-CiprianMuresan** [comment]
[network_console_output.txt](https://github.com/mozilla/remote-settings/files/10083720/network_console_output.txt)

Attaching the output of the Network tab while trying to load recipes. Looks like there are a couple of requests to https://stage.normandy.nonprod.cloudops.mozgcp.net which resolve in 502 error codes.

**Comment by smarnach** [comment]
I can reproduce this issue as well – thanks for reporting. I'll try to track this down and fix it.

**Comment by smarnach** [comment]
I was able to track down this problem, and it's fixed for me now. The root cause was this code, which ended up picking the wrong database server IP address: https://github.com/mozilla-services/cloudops-infra/blob/master/projects/normandy/tf/modules/postgres/outputs.tf
