### ISSUE TITLE
Use default dataset when we haven't done the fetch yet

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#35]

**Comment by mostlygeek** [comment]
`undefined` ?

**Comment by leplatrem** [comment]
We could say that if the local database is empty, when we call `get()` for the first time it performs a sync :) 

Plus, we could also generalize what we have done in blocklists about sync:
- a JSON dump is shipped in the Gecko source tree (https://bugzilla.mozilla.org/show_bug.cgi?id=1451040)
- when the local database is empty, the client loads the dumps 
- when the sync starts it only catches up from what was changed remotely since the dump was shipped

See https://bugzilla.mozilla.org/show_bug.cgi?id=1451050 :)

**Comment by leplatrem** [comment]
> Empty array, [] ?

This could also mean that no data matches the target

**Comment by mostlygeek** [comment]
How about this...?

- `.get()` only goes through what it has locally, if db is empty it'll return `[]`
- we encourage people to set `.on()` listeners

By having people make use of `.on()` it'll decouple updates from usage of the data.  Then we can update in a variety of ways ... 

- sync on Fx startup
- sync on the 24hr timer
- broadcast / push based sync
- sync if database is empty
- sync if it hasn't been updated in _t_ hours
- etc

**Comment by mostlygeek** [comment]
@leplatrem do you have enough information for this to make a decision?

**Comment by leplatrem** [comment]
I think I'd prefer this strategy:

When `get()` is called on a db that was never synchronized, we look if there's a dump in the source tree for this collection and load it, if not we return `[]`.

Otherwise it seems a bit inconsistent to ship a default dataset in the source tree and not use it as the default returned value.

This was declined as:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1451050
- https://bugzilla.mozilla.org/show_bug.cgi?id=1451040

**Comment by leplatrem** [comment]
Submitted https://bugzilla.mozilla.org/show_bug.cgi?id=1451050 for review

**Comment by leplatrem** [comment]
Shipped in 1451050. Will load local dump on `.get()` when DB is empty.
