### ISSUE TITLE
We are not able to successfully connect to Normandy stage environment and create/edit/disable recipes

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/remote-settings#416]
**[Affected Versions]:**
- Firefox Nightly 114.0a1
- Firefox Beta 113.0b3
- Firefox Release 112.0

**[Affected Platforms]:**
- Windows 10 x64
- macOS 12.4
- Ubuntu 20.04 x64

[Prerequisites]
- Have access to the Normandy stage environment.
- Have LDAP accounts.
- Be connected to OpenVPN with a valid account.

**[Steps to reproduce]:**
1. Open the Firefox build and install the Normandy Dev Tools addon.
2. Click the Normandy Dev Tools button from the browser toolbar.
3. Login with LDAP account.
4. Switch to the "Stage" environment.
5. Click on an enabled recipe and try to disable it.
6. Observe the behavior.

**[Expected results]:**
- The recipe is successfully disabled.

**[Actual results]:**
- A "An Error Occurred: "NetworkError when attempting to fetch resource." error is displayed and the recipe cannot be disabled. -

**[Notes]:**
- The Normandy production environment doesn't seem to be affected.
- Usually, we have a green dot displayed on the avatar when we are successfully connected to the Normandy stage environment, but now the greed not is no longer displayed.
- Attached is a screen recording of the issue.

https://user-images.githubusercontent.com/19226534/232748187-4157afba-b202-42f7-81f1-8905ecce9f52.mp4

**Comment by ahoneiser** [comment]
the remote-settings stage environment has been migrated to GCP last week, this is most likely due to changed endpoint names .. will fix this with https://github.com/mozilla-services/cloudops-infra/pull/4819 :slightly_smiling_face:

**Comment by smarnach** [comment]
Yup, that's indeed the reason the stage admin API is crashlooping.

**Comment by ahoneiser** [comment]
@SoftVision-CosminMuntean, I've deployed the new URLs to stage, can you re-check?

**Comment by SoftVision-CosminMuntean** [comment]
@ahoneiser I have verified this issue and is no longer reproducible. We are able to create/edit/disable recipes with Normandy Devtools. Considering this, I will close this issue as verified - fixed.
