### ISSUE TITLE
Enhance the Quality Standards score to exceed 80%

### ISSUE THREAD

**Issue by grahamalama** [mozilla/remote-settings#419]
* [x] `repo-standard-files`, `repo-readme-sections`, `repo-makefile-targets`, `test-lint-secrets`, `test-pull-requests-labels` #418 
* [x] `release-tag-only`: use generated changelog and get rid of `VERSION` file
* [x] `monitoring-requests-id`

**Comment by leplatrem** [comment]
Done in https://github.com/mozilla/remote-settings/pull/418

**Comment by leplatrem** [comment]
Done, missing checks listed in latest score card https://mozilla.github.io/syseng-pod/quality-standards/#service-Remote%20Settings
