### ISSUE TITLE
Move Focus experiments to the main bucket

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#44]
A bucket and reviewable collection was created in August 2017. But no records have been created yet.

Ben could you please check with the team if they could migrate to the `main` bucket instead ? (basically, do they have clients in the wild that poll `focus/experiments` and/or can they change them to `main/focus-experiments` ?

Thanks!

See https://bugzilla.mozilla.org/show_bug.cgi?id=1394515

**Comment by mostlygeek** [comment]
Sure I can follow up.

**Comment by leplatrem** [comment]
I don't know if this is documented, but I know that a Sebastian implemented it in Java using raw HTTP requests in Android (ie. without any kinto-offline.java lib) https://bugzilla.mozilla.org/show_bug.cgi?id=1197720, and AFAIK the signatures aren't verified, even if it is enabled on the server  https://bugzilla.mozilla.org/show_bug.cgi?id=1356585

**Comment by mostlygeek** [comment]
I sent an email to Sebastian letting them know that we'll be cleaning up the `focus` bucket and to let me know if they have any objections to it. 

Will keep this issue updated.

**Comment by leplatrem** [comment]
WIP https://bugzilla.mozilla.org/show_bug.cgi?id=1456535 and https://github.com/mozilla-services/cloudops-deployment/pull/1893

**Comment by leplatrem** [comment]
Done in STAGE, waiting for PROD

**Comment by leplatrem** [comment]
Done
