### ISSUE TITLE
How do we do end to end testing of remote-settings?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/remote-settings#45]
With the changes we've done and have planned it's not clear what the testing / verification process is for remote-settings.  What procedure or guidance can we provide Product Integrity to verify and test changes we've landed in Firefox? 

This is especially important for V2 as we'll be marketing the new features more and expect to support more use cases.

**Comment by leplatrem** [comment]
I wrote some docs at https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=66655528 I will send an email to product integrity :)

**Comment by mostlygeek** [comment]
We figured this out with PI during the work week. Closing.
