### ISSUE TITLE
Write documentation from POV of settings editor

### ISSUE THREAD

**Issue by glasserc** [mozilla/remote-settings#47]
Something that would have helped https://bugzilla.mozilla.org/show_bug.cgi?id=1450144.

The existing docs in the mozilla-central tree are more focused on Gecko-based implementers. We should have something that explains where settings are stored, how they are edited, how signoff works, etc. The https://github.com/Kinto/kinto-signer README contains some of this information but it's mixed in with stuff a user probably doesn't care about (server-side settings, the Content-Signature protocol, CDN invalidations...).

**Comment by leplatrem** [comment]
You are right, there are many incomplete/inaccurate source of docs....
- https://wiki.mozilla.org/Firefox/Kinto
- https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=66655528
- https://firefox-source-docs.mozilla.org/services/common/services/RemoteSettings.html

IMO: 
- firefox-source-docs : API docs for Gecko developers
- Mana : for OPS and staff (add new collection, new collaborators, etc.)
- Wiki : list existing use cases, pointers to community, FAQ etc.
- kinto-signer docs: remote settings server / UI developers

I wanted to tackle this in #13 and #31

**Comment by leplatrem** [comment]
I updated the docs on Mana https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=66655528 @glasserc  r?

**Comment by glasserc** [comment]
Which part is the part for the settings editor? I think there's still a lot of stuff mixed together here, and I think you still assume too much knowledge on the part of the reader.

Ideally I'd like something that goes from zero to editor, so it should start like "Remote Settings is a product that we use to ship data to Firefox. It's implemented using Kinto", and go through "Signing works as follows: editors modify data in [...]" and end at "In order to create a new Remote Settings collection in prod, open a PR on [...]".

**Comment by leplatrem** [comment]
I improved it a bit :)  r?

**Comment by leplatrem** [comment]
Thanks! Let's close it, and wait for some concrete feedback :)
