### ISSUE TITLE
Stylo blocklist use-case ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#48]
A while ago we were in touch with Stylo team, they wanted a list of domains that should use the old Gecko style system instead of Stylo

Creating new remote settings was not as fancy as it is now, and in the end, they ended up using a preference... that they update via a system-addon

See https://bugzilla.mozilla.org/show_bug.cgi?id=1403077#c49

Maybe we should get back to them and see if they'd be interested to use our new stuff :)

**Comment by mostlygeek** [comment]
There wasn't much interest. Closing.
