### ISSUE TITLE
Passwords recipes use case ? 

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#49]
The password manager needs some per-website rules to target the right fields on the page. 

Currently, they are managed via a JSON file in the source tree:
https://searchfox.org/mozilla-central/rev/795575287259a370d00518098472eaa5b362bfa7/toolkit/components/passwordmgr/content/recipes.json

It's a perfect use-case for RemoteSettings, where some admins could fix passwords selectors etc. out of release cycles.

AFAIK it was abandoned because of lack of resources and/or clear plan... Now that we have fancy RemoteSettings we could get back to them!

See https://bugzilla.mozilla.org/show_bug.cgi?id=1134852

**Comment by mostlygeek** [comment]
I reached out to them and there wasn't much interest. Closing for now. Maybe reopen or create a new issue for this in the future.
