### ISSUE TITLE
Enabling the "simple-review" workflow from the classic admin panel is not obvious

### ISSUE THREAD

**Issue by travis79** [mozilla/remote-settings#571]
While looking at the simple-review page, I accidentally clicked the button to return to the classic admin panel. After this I couldn't find any way in the UI to return to the simple-view, and trying to go directly to the URL I would just end up getting redirected back to https://remote-settings.mozilla.org/v1/admin/#/buckets/main-workspace/collections/nimbus-desktop-experiments/records.

I finally managed to find the setting that controlled whether the simple-review was visible in LocalStorage and flipped it using DevTools.

After mentioning this to @leplatrem, Mathieu pointed out that the button was at the bottom of the records page. It didn't occur to me that there might be controls at the bottom of the page, hidden below the fold.

I think that putting this button in a more obvious spot, maybe underneath the "Login" and "Documentation" buttons in the upper-right of the page, or even in the same bar as the Doc and Login button might make it more discoverable "above the fold" of the page.

**Comment by alexcottner** [comment]
Throwing out some options, see screenshot and descriptions below. 

Option 1: Fixed to top-right corner of records page, only in one place.
Option 2: Under/near "Rollback changes" button
Option 3: In tab container bar floating to the right. This one may feel out of place, but it seems likely that most people will be using the simple-review UI all the time.
Option 4: To the right of the "Create record" and "Bulk create" buttons. People without record:create permissions will only see this button. I'll probably turn these into a button group if we choose this option.

![image](https://github.com/mozilla/remote-settings/assets/148472676/c5558e13-7f8e-4974-bfe6-b5a7dde88b01)

**Comment by travis79** [comment]
I like either Option 1 or 3. That feels like the first place I would go looking for settings, and I agree, most people shouldn't get into this state on purpose (unlike me and my uncontrolled clicking that accidentally landed me here 😅 )

**Comment by alexcottner** [comment]
PR has been merged, will be fix in next release (probably next week).
