### ISSUE TITLE
Add high-level API for remote settings in Gecko

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#6]
Something like:
```js
try {
   providers = await RemoteSettings.get("search.providers");
   for(const p of providers) {
     UI.addSearch(p, ...);
   }
} catch(e) { … }
```

Or, to be notified when some changes occur:
```js
RemoteSettings.onChange("some key", (changes) => {
  …
})
```

**Comment by mostlygeek** [comment]
Do you think we should have `RemoteSettings` have functions for handling attachments? 
I do think we'll need to have some inspection / debugging api methods. If possible, in the browser console if we could `RemoteSettings.inspect("my.key")` that would be really nice for adhoc testing.

**Comment by leplatrem** [comment]
> Do you think we should have RemoteSettings have functions for handling attachments?

I don't think we should do too much for now, and let developers handle the attachments the way they want. It would just be like this actually:

```js
const entries = await RemoteSettings.list("fonts");

await Promise.all(entries.map(async ({attachment: {url}}) => {
  const r = await fetch(url);
  doSomethingWithBinary(r.body)
}));
```

> if we could RemoteSettings.inspect("my.key") that would be really nice for adhoc testing.

Yes, why not, that's trivial

**Comment by leplatrem** [comment]
Some ideas: 

### onChange()

By calling `RemoteSettings.onChange()` developers «register» their remote settings collection. This way it gets synchronized on every poll, and the provided callback is called with the changes object.
```js
  RemoteSettings.onChange(id: string, 
                          async (client: RemoteSettingsClient, changes: RemoteSettingsChanges) => {},
                          options: object = {});
```


#### changes object

It would be a simple object with at least those 4 fields:

```js
  {
    all: [{ ... full list of records }],
    created:   [{
      id: ..
      last_modified: ..
      ..
    }],
    updated:   [],
    deleted:   [],
  }
```

> Note: The lists would be already filtered according to targeting rules.

#### Examples

The simplest way to use it, with all default values would be:
```js
  RemoteSettings.onChange("fonts", async (client, {all: entries}) => {
    // entries.forEach(...)
  });
```

A complex way — for existing blocklist use-cases for example — would be:

```js
  RemoteSettings.onChange(Services.prefs.getCharPref(PREF_BLOCKLIST_ONECRL_COLLECTION),
                          updateCertBlocklist, {
                            bucketName: Services.prefs.getCharPref(PREF_BLOCKLIST_BUCKET),
                            lastCheckTimePref: PREF_BLOCKLIST_ONECRL_CHECKED_SECONDS,
                            signerName: "onecrl.content-signature.mozilla.org",
                          });
```

Or with some attachments for example:

```js
  RemoteSettings.onChange("fonts", async (client. {created, updated, deleted}) => {
    // Delete attachments from disk
    await Promise.all(deleted.map(({attachment: {filename}}) => {
      OS.remove(`file://profile/${filename}`);
    });
    // Save attachments to disk
    await Promise.all(created.concat(updated).map(({attachment: {location, filename, size}}) => {
      if !enoughSpace(size) {
        throw new Error("disk full");
      }
      return download(location, `file://profile/${filename}`);
    });
    // Reload from disk
    Services.reloadFonts();
  });
```

> Note: What happens if multiple calls to `onChange()` are made? IMO only one client should be registered, but every callback should be called in the order they were registered.

### list()

The `list()` returns the full list of records, accepts a `bucketName` option like `onChange()` plus some filters/sorting (see [kinto.js docs](http://kintojs.readthedocs.io/en/latest/api/#listing-records))

```js
  const entries = await RemoteSettings.list("fingerprints");
```

or
 
```
const entries = await RemoteSettings.list("certificates", {
  bucketName: Services.prefs.getCharPref(PREF_BLOCKLIST_BUCKET),
  filters: {issuer: "Mozilla Corporation"},
  order: "-revocationDate",
})
```

### inspect()

Information that would be required to be returned (as object): 

Global:
- server
- list of registered settings collections
- local timestamp
- server timestamp
- last check
- server backoff
- clock skew
- root hash

For each collection:
- collection name
- bucket name
- local timestamp
- server timestamp
- collection metadata
- last poll date
- signer name

> Note: would be used for `about:remotesettings` for example.

### configure()

Abstraction on top of preferences to change configuration between STAGE/PROD, and PREVIEW/FINAL 

- server
- blocklists bucket
- remote settings bucket

> Note: would be used for about:remotesettings for example.

**Comment by mostlygeek** [comment]
I think the API should only two functions for accessing data:  `get()` and `onChange()`. 

```js
function handleData(mydata) { console.log(mydata); }

// .get 
providers = await RemoteSettings.get("search.providers");
handleData(providers);

// onChange
RemoteSettings.onChange("search.providers", handleData)
```

These functions are simple on purpose: 

- they are single value
- they stick to the design philosophy of us just being a tunnel
- they expose very little (or nothing) of the underlying kinto mechanics
- they hide details like signing, verification, targeting, etc
- compatible with the future broadcast API. `onChange` can be triggered by polling or a push notification

The other functions, `client()`, `inspect()`, `configure()`, etc are for development and debugging purposes.  Mostly for us when we're trying to troubleshoot. These aren't functions we would encourage users of `RemoteSettings` to use.

**Comment by leplatrem** [comment]
> I think the API should only two functions for accessing data: get() and onChange().

Ok I can rename `list()` to `get()`

> they expose very little (or nothing) of the underlying kinto mechanics

I really want this too. But I also really want the former blocklist clients to use this remote settings API. That's why I presented the advanced options I had in mind for that purpose (like bucketName, signer etc.). We can keep those options secret of course.

I'll edit my comment to make that distinction clearer.

**Comment by leplatrem** [comment]
I wonder if doing it like this would not be more flexible and clearer WRT advanced options:


```js

const entries = await RemoteSettings("search.providers").get();

RemoteSettings("search.providers").onChange(({data}) => { ...});

```

It would allow to get rid of that `client()` method above and it would allow to
store a reference between calls.

```js

const oneCRL = RemoteSettings("certificates", {
  bucketName: "blocklists",
  signerName: "onecrl.content-signature.mozilla.org",
})

oneCRL.onChange(updateCertBlocklist);

button.on("click", async () => {
  const entries = await oneCRL.get();
  window.alert(`There are ${entries.length} entries.`);
})


```

**Comment by peterbe** [comment]
I've been staring at this and I don't know if I have much to add. 

My mind is quite tainted of having used Google Firebase a lot. I definitely like the idea of `const rs = RemoteSettings(config); rs.operation(data => {... })`.

One idea that comes to mind, much inspired by Firebase's database, is to use `.on` and use different "sub operations". E.g. 
```javascript
const rs = RemoteSettings(config);

// Extract all without continued listening
rs.values('search.providers', 'once', entries => {
  console.log("last updated", entries[0].metadata.modTime);
  console.log(`${entries.length} search providers`);
});

// Create a subscriber/listener but filter by operation
rs.values('search.providers', 'added', item => {
  assertEqual(item.metadata.operation, 'added')
  console.log('New search provider', item.metadata.createTime);
  console.log('Provider:', item.entry);
});

// Register a second listener but this time only for updates
rs.values('search.providers', 'updated', item => {
  assertEqual(item.metadata.operation, 'updated')
  console.log('Provider:', item.entry);
});

// And removed ones (if possible)
rs.values('search.providers', 'removed', item => {
  assertEqual(item.metadata.exists, false)
  console.log('Provider:', item.entry);
});

// Listen for any change
rs.values('search.providers', 'all', item => {
  console.log('Provider:', item.entry, 'Was:', item.metadata.operation);
});
```

Or perhaps, use the concept of a "reference by ID":
```javascript
const rs = RemoteSettings(config);
const fonts = rs('fonts');
fonts.values('removed', ({ entry }) => {
  OS.remove(`file://profile/${entry.filename}`);
});
```

Just some guttural early feedback.

**Comment by glasserc** [comment]
Just to confirm, we're doing filtering on the client side, right? I guess we have to if we want to re-use our existing signature infra..

One thing that jumps out at me is the feedback that :rnewman gave me on my global-broadcast API. He basically wanted something that could be:

- lazy (doesn't initialize the caller of this remote settings pipeline until they have information they actually need to deal with)
- not tied to JS semantics (possible to implement using Rust or a completely external process, although obviously at present, we're building on top of existing JS code)
- restartable because of the ways processes can get interrupted on Mobile

What he suggested was, instead of relying on a Python-esque module that registers interest in events on import, for me to have a list of components that get looked up and initialized when notifications come in, and that this list gets persisted across restarts. Elements can get added to the list when they are imported, with the understanding that because I persist them, they will remain registered on next startup even before they get imported.

I'm not sure this type of API advice is useful for you.

**Comment by gijsk** [comment]
I have to admit I don't have much to add, except that I'm struggling to see how the API proposed here maps to the blocklist client stuff we have at the moment. I *think* what you're saying is that the blocklist service would just create the blocklist remote settings client, call `.get()` to get *all* the current (local) data (asynchronously, of course), and register a change handler that will get notified when the data changes, and then the blocklist service itself would be responsible for answering queries from the addon/plugin/gfx code about whether something is blocked or not (and that's out of scope for the API we discuss here) -- is that more or less correct?

Assuming I'm understanding this correctly, I wonder if there'd be any use for delegating more of the "is there a data point/entry for an item with these criteria" functionality into this code or not, rather than forcing the consumers of the API to cache all the data in memory, which will increase memory footprint. So have some query language that can be used with a `.search` or `.find` method that will only return matching entries. Or something. But perhaps I'm way off base! :-)

**Comment by leplatrem** [comment]
Yes Gijs! I haven't explored yet every details of how the `nsBlocklistService` would directly be plugged to it, and I was more into suggesting a multi-purpose API for remote settings.

But yes, what you describe makes sense. Something like this:
- The remote settings part is in charge of keeping up with the server data, and provides an API list/query the local data
- The blocklist service responds to addon/plugin/gfx queries by using that API

Regarding the ability to search for records, we already have a filter by attribute. But I think we could also pass a «filtering» function that returns true/false provided an item. Because for example -- if I remember well -- the way we filter items in the blocklist service is going to be hard to express with a query language.

Thanks for your feedback :) 

> Note: I already a few steps forward in [Bug 1397230](https://bugzilla.mozilla.org/show_bug.cgi?id=1397230) which landed \o/ https://searchfox.org/mozilla-central/rev/003262ae12ce937950ffb8d3b0fa520d1cc38bff/services/common/blocklist-clients.js#136-166

**Comment by leplatrem** [comment]
Done.

Last bit was https://bugzilla.mozilla.org/show_bug.cgi?id=1454315
