### ISSUE TITLE
Real-time Uptake Telemetry

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#90]
Currently we use Categorical Histograms for uptake and status.

Should we use the Events API ? What would be the upsides / downsides ?

https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/events.html

(added by :mostlygeek) 
remote-settings currently uses uptake-telemetry which sends a histogram which has a large collection of states:  https://searchfox.org/mozilla-central/source/services/common/uptake-telemetry.js

**Comment by mostlygeek** [comment]
My main want here is more precise operational metrics.  remote-settings is about keep settings/lists evergreen.  So we should be able to measure how good of a job we are doing keeping Fx updated. 

We should: 
 
1. be able to create alerts to monitor the system
1. be able to see failure rates and have data showing the reason
1. know how long it takes to fetch and updates (network, system latency)
1. be able to differentiate polling vs push triggered updates
1. others?

**Comment by mostlygeek** [comment]
@sunahsuh which of these would be better / easier to create reports on: 

```
{ type: "success"}
{ type: "error:network" }
{ type: "error:indexdb" }

vs

{ type: "error", reason: "network"}
{ type: "error", reason: "indexdb"}
```

**Comment by leplatrem** [comment]
Shipped in Fx67 :) 
https://bugzilla.mozilla.org/show_bug.cgi?id=1517469
https://bugzilla.mozilla.org/show_bug.cgi?id=1535962
