### ISSUE TITLE
Disable self service in STAGE

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#94]
In STAGE we wanted to have self-service of collections, so that users can test their code without us being in the loop.

But some limitations make it difficult in practice:
- the lambda user is not allowed to write by default. If the developer does not allow the lambda account explicitly, then the lambda fails to refresh the signatures. 
- if users can create collections, then it makes sense to allow them cleanup their stuff. Since creating a collection also creates a preview collection and the main one, we gave the permissions to delete to every staff in the preview and main bucket. Since kinto does not distinguish the write permission from delete, we had to give the write perm to every staff. But write also allows to edit stuff in the main bucket directly, and some users did, which obviously broke signature verification. 
- when rolling out to PROD, we overwrite the collection in STAGE anyway, and don't take advantage of what developers designed there.
- when a lambda fails, ops are usually reluctant to deploy new versions or rollout config changes. Which makes the whole process slower, for no real reason

Each of this point can find technical solutions, but the easiest way would be to disable self-service in STAGE and manage everything via bugzilla + PR on .yml manifests.

**Comment by mostlygeek** [comment]
The original goal was to reduce friction for new developers to start playing with it to get a feel for the APIs.  Looking at how we've interacted I think doing onboarding and 1:1 with teams is a more effective approach. 

So I'm +1 to removing the self service.  Do we have docs somewhere describing how we onboard.  Off the top of my head: 

1. 1:1 / video introduction / consultation for a team.  
   - Is RS the right solution? 
   - Guidance on using RS in your client code?  
   - Share dev documentation 
   - **does RS meet your needs? Do you want to move forward**
1. Developers files bugs with a template w/ the information we need:
   - users to create
   - name of collection
   - tracking bug, closed when prod+new client code has been shipped
   - we use this bug to track stage, prod deployments and other dev notes
   - ??? 
1. We create STAGE PR for cloudops and schedule the deployment to stage
1. Provide whatever support we can to developers
1. We create PROD PR for cloudops and schedule the deployment to prod

**Comment by glasserc** [comment]
It seems like this question has been addressed and the answer is "yes". What are the remaining action items here?

**Comment by leplatrem** [comment]
The last step consists in removing the write permission to staff and leaving it just to user used by QA scripts. 

If we don't want to let QA test collection creation, we should modify their scripts and remove the permission to everybody. But I believe it makes sense to test collection creations...
